import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import Section1 from '../components/Section1'
import Section2 from '../components/section2'
import Resume from '../components/Resume'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Section1 />
      <Section2 />
      <Resume />
      <Footer />
    </div>
  )
}
